// Copy dictionary — ported verbatim from the v48 build. Single source of truth for UI text.

export const copy = {
  brand: {
    appName: "Innerly",
    tagline: "Self-awareness · Action",
    libraryLabel: "Library",
    streakSingular: "Day on Innerly",
    streakPlural: "Days on Innerly",
  },
  nav: {
    dashboard: "Dashboard",
    reflect: "Reflect",
    dailyPlan: "Daily Plan",
    manifestation: "Manifestation",
    visionBoard: "Vision Board",
    blog: "Blog",
    tutorials: "Tutorials",
    history: "History",
    settings: "Settings",
  },
  dashboard: {
    breadcrumb: "Innerly / Home",
    greeting: "How are you feeling today, {name}.",
    welcomeToast: "Welcome to Innerly, {name}.",
    featureReflectTitle: "Reflective Journal",
    featureReflectDesc: "Move through what happened, why, and what you'll do next.",
    featureDailyPlanTitle: "Daily Plan",
    featureDailyPlanDesc: "Set quiet intentions. One clear step at a time.",
    featureManifestationTitle: "Manifestation",
    featureManifestationDesc: "Grounded affirmations and goal clarity.",
    featureVisionTitle: "Vision Board",
    featureVisionDesc: "Keep what you're building toward visible.",
    todayTitle: "Today's plan",
    todayOpenLink: "Open plan",
    todayEmpty: "No actions yet — open a goal and add what you'll do today.",
    todayMore: "more in your plan",
    remindersEyebrow: "Reminders to yourself",
    remindersTitle: "What you're working on",
    remindersDesc: "Drawn from your reflections. Tick the ones you're honouring.",
    remindersProgress: "you're acting on",
    remindersAllClear: "You're acting on all of them. Beautifully done.",
    remindersCta: "New reflection",
    nightEyebrow: "Before you rest",
    nightTitle: "Did today move you forward?",
    nightAsk:
      "Have you grown, even a little, since yesterday? You can note it — or simply let the day close.",
    nightYes: "Yes — I'll note it",
    nightNo: "Not tonight",
    nightWritePrompt: "A few small ways today was different from yesterday.",
    nightSave: "Save",
    nightSaved: "Noted, and held. Rest well — tomorrow is another small step.",
    nightSkipped: "That's okay. Some days we just rest. Goodnight.",
    nightPlaceholders: [
      "I paused before reacting.",
      "I started the thing I was avoiding.",
      "I was kinder to myself.",
    ],
    blogEyebrow: "From the blog",
    blogReadMore: "Read more",
  },
  reflect: {
    breadcrumb: "Innerly / Reflect",
    title: "Reflective Journal",
    subtitle: "Honest reflection. No performance.",
    step1Title: "What felt heavy today?",
    step1Hint:
      "Write freely — name as many moments as you need. You'll reflect on each one through the next steps.",
    step2Title: "Why do you think this happened?",
    step2Hint: "Answer each situation separately, in your own words.",
    step3Title: "Pause & review",
    step3Hint: "Take a moment to slowly re-read what you wrote.",
    step3Intro:
      "Sometimes patterns become clearer when you see your thoughts in front of you. Select any text to highlight or underline what stands out — triggers, contradictions, fears, repeated ideas.",
    step4Title: "What can you do differently next time?",
    step4Hint:
      "This is where you speak to yourself. Write freely — kindly, like advice to a friend.",
    gentleGate:
      "Add at least one moment in step one first — this reflection grows from what you noticed today.",
    continueLabel: "Continue",
    saveLabel: "Save Reflection",
    completionTitle: "Awareness is the first step to change.",
    completionContinue: "Continue to Daily Plan",
    completionBack: "Back to Dashboard",
    momentPlaceholders: [
      "I didn't complete my assignment as planned.",
      "I had an argument with my friend.",
      "I ignored something important.",
    ],
  },
  manifestation: {
    breadcrumb: "Innerly / Manifestation",
    title: "Manifestation",
    subtitle: "Name it clearly. Align to it daily.",
    goalsTitle: "What do you want to manifest?",
    goalsDesc:
      "Write in the present tense, as if it is already true. Be specific and sensory — what does it look and feel like? Add as many as you wish.",
    goalPlaceholder: "I am… / I have… / I feel…",
    addAnother: "Add another",
    affirmationsTitle: "Affirmations",
    affirmationsDesc: "Short, present-tense truths to return to. Add as many as you like.",
    affirmationsAddLabel: "Add an affirmation",
    affirmationPlaceholders: [
      "I am becoming more grounded each day.",
      "I trust myself to follow through.",
      "I am worthy of the life I'm building.",
    ],
    gratitudeTitle: "Gratitude",
    gratitudeDesc: "Name a few things you're grateful for, as if they're already here.",
    gratitudeAddLabel: "Add gratitude",
    gratitudePlaceholders: [
      "I'm so thankful and grateful for my health.",
      "I'm so thankful and grateful for the people who support me.",
      "I'm so thankful and grateful for this quiet morning.",
    ],
    releaseTitle: "Release & Let Go",
    releaseDesc:
      "Name the things you're ready to release — fears, old stories, or patterns that no longer serve you. Writing it down makes space for what you're calling in.",
    releaseAddLabel: "Add a release",
    releasePlaceholders: [
      "I release my need to control what I cannot change.",
      "I let go of the fear of not being enough.",
      "I free myself from carrying the weight of others' expectations.",
      "I release the story that I have to have it all figured out.",
      "I let go of resentment that no longer serves my growth.",
    ],
    saveLabel: "Save manifestation",
    savedTitle: "Saved. Held gently.",
    savedText:
      "Would you like to bring this to life on your Vision Board — or see what you've already gathered there?",
    savedGoVision: "Go to Vision Board",
    savedLater: "Maybe later",
  },
  dailyPlan: {
    breadcrumb: "Innerly · Daily Plan",
    title: "Daily Plan",
  },
  visionBoard: {
    breadcrumb: "Innerly · Vision Board",
    title: "Vision Board",
    subtitle: "What you're building toward — gathered, by year, and kept close.",
  },
  blog: {
    breadcrumb: "Innerly · The Journal",
    title: "The Journal",
    subtitle: "Reflections on self-awareness, patterns, and intentional growth.",
  },
  tutorials: {
    breadcrumb: "Innerly / Tutorials",
    title: "Tutorials",
    subtitle: "Short guides to get the most out of Innerly.",
  },
  history: {
    breadcrumb: "Innerly / History",
    title: "History",
    subtitle: "Look back, and notice how you've moved.",
  },
  settings: {
    notificationsTitle: "Notifications",
    notifAllowLabel: "Allow notifications",
    notifAllowDesc: "Gentle nudges and reminders from Innerly.",
    notifDailyLabel: "Daily reflection reminder",
    notifDailyDesc: "A quiet evening prompt to check in.",
    notifWeeklyLabel: "Weekly report",
    notifWeeklyDesc: "Your 7-day summary of growth and patterns.",
  },
} as const;

export function fill(template: string, vars: Record<string, string>) {
  return template.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? "");
}
